import { useEffect, useState } from 'react';
import { ArrowRight, CalendarClock, Check, CheckCircle2, ChevronRight, Clock3, Droplets, History, LayoutDashboard, LogOut, ShieldCheck, Sparkles, WashingMachine, Wrench, X } from 'lucide-react';
import { createGateway } from './gateway';
import type { Action, Gateway, Machine, Snapshot } from './types';

const gatewayPromise = createGateway();
const initial: Snapshot = {user: null, machines: [], sessions: [], reports: [], loading: false, error: ''};
const time = (ms: number) => new Date(ms).toLocaleTimeString([], {hour: '2-digit', minute: '2-digit'});
const remaining = (end: number, now: number) => {const s = Math.max(0, Math.ceil((end - now) / 1000)); return `${Math.floor(s / 60).toString().padStart(2, '0')}:${(s % 60).toString().padStart(2, '0')}`;};

export default function App() {
  const [gateway, setGateway] = useState<Gateway>();
  const [configurationError, setConfigurationError] = useState('');
  const [state, setState] = useState(initial), [page, setPage] = useState('overview'), [floor, setFloor] = useState('All floors');
  const [now, setNow] = useState(Date.now()), [selected, setSelected] = useState<Machine | null>(null), [duration, setDuration] = useState(45);
  const [busy, setBusy] = useState(false), [notice, setNotice] = useState(''), [error, setError] = useState(''), [dialog, setDialog] = useState<{kind: Action; machine?: Machine; reportId?: string} | null>(null), [detail, setDetail] = useState('');
  useEffect(() => {
    let disposed = false, stop: (() => void) | undefined;
    gatewayPromise.then(current => {
      if (!disposed) {setGateway(current); stop = current.subscribe(setState);}
    }).catch(error => {if (!disposed) setConfigurationError(error instanceof Error ? error.message : 'Configuration is incomplete.');});
    return () => {disposed = true; stop?.();};
  }, []);
  useEffect(() => {const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer);}, []);
  useEffect(() => {if (!notice) return; const timer = setTimeout(() => setNotice(''), 6000); return () => clearTimeout(timer);}, [notice]);
  const active = state.sessions.find(s => s.status === 'active' && s.endsAt > now) || state.sessions.find(s => s.status === 'active'), available = state.machines.filter(m => m.status === 'online' && m.activeEndsAt <= now);
  const availableByFloor = state.machines.filter(m => floor === 'All floors' || m.floor === floor);
  async function work(action: () => Promise<void>, message: string) {setBusy(true); setError(''); try {await action(); setNotice(message);} catch (error) {setError(error instanceof Error ? error.message : 'Please try again.');} finally {setBusy(false);}}
  async function act(name: Action, payload: Record<string, unknown>, message: string) {await work(() => gateway!.act(name, payload), message);}
  const date = new Date(now).toLocaleDateString('en-IN', {weekday: 'long', month: 'short', day: 'numeric'});

  if (!state.user) return <main className="signin"><div className="signin-card"><div className="brand"><span className="brand-icon"><Droplets size={22} /></span>WashBook<span className="brand-dot">.</span></div><div className="signin-art"><WashingMachine size={108} strokeWidth={1.15}/><span className="bubble a"/><span className="bubble b"/><span className="bubble c"/></div><span className="eyebrow">A SMALL UPGRADE TO HOSTEL LIFE</span><h1>Laundry,<br/>without the wait.</h1><p>Check a machine. Reserve your time.<br/>Get on with the rest of your day.</p><button className="primary signin-button" disabled={busy || !gateway} onClick={() => work(() => gateway!.signIn(), 'You’re signed in.')}>
    {gateway?.demo ? 'Explore the demo' : gateway?.emulator ? 'Enter local emulator' : 'Continue with Google'}<ArrowRight size={18}/></button>
    {gateway?.demo && <small>Interactive demo. Your changes stay in this browser.</small>}{(error || configurationError) && <p className="error-text" role="alert">{error || configurationError}</p>}<div className="signin-footer"><CheckCircle2 size={15}/> One resident. One active booking.</div></div></main>;

  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-icon"><Droplets size={21}/></span>WashBook<span className="brand-dot">.</span></div><div className="hostel-chip"><span className="hostel-monogram">N</span><div>North Block<small>Hostel laundry room</small></div></div><nav aria-label="Main navigation">{[{id:'overview',label:'Overview',Icon:LayoutDashboard},{id:'session',label:'My session',Icon:CalendarClock},{id:'history',label:'History',Icon:History},{id:'guide',label:'Laundry guide',Icon:Sparkles}].map(({id,label,Icon}) => <button key={id} className={page === id ? 'nav-item active' : 'nav-item'} onClick={() => setPage(id)}><Icon size={18}/>{label}{id === 'session' && active && <span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="tip"><span className="eyebrow">GOOD LAUNDRY ETIQUETTE</span><p>Your load is done?<br/>Let the next one begin.</p><span>Free up your machine when you finish.</span></div><button className="profile" onClick={() => work(() => gateway!.signOut(), '')}><span className="avatar">{state.user.name[0]}</span><span>{state.user.name}<small>{state.user.isAdmin ? 'Administrator' : 'Resident'}</small></span><LogOut size={16}/></button></div></aside>
  <main className="content"><header className="topbar"><div className="breadcrumb">North Block <ChevronRight size={13}/> Laundry room</div><div className="live-label"><span/>Live availability</div></header>
  {gateway?.demo && <div className="demo-banner"><span>Demo mode · bookings are saved in this browser</span><button onClick={() => gateway!.toggleDemoAdmin()}>{state.user.isAdmin ? 'Resident view' : 'Try admin view'}<ArrowRight size={13}/></button></div>}
  {(error || state.error) && <div className="alert error" role="alert">{error || state.error}<button aria-label="Dismiss error" onClick={() => setError('')}><X size={16}/></button></div>}
  {notice && <div className="alert success" role="status"><CheckCircle2 size={17}/>{notice}</div>}
  <div className="page-heading"><div><span className="eyebrow">{date}</span><h1>{page === 'overview' ? `Hey, ${state.user.name.split(' ')[0]}.` : page === 'session' ? 'Your laundry, on track.' : page === 'history' ? 'A little laundry history.' : 'Make every load count.'}</h1><p>{page === 'overview' ? 'A fresh load. A clear schedule. Let’s make it happen.' : 'Everything you need for a smoother laundry day.'}</p></div><span className="room-badge"><Droplets size={16}/>North Block laundry</span></div>
  {state.loading && <div className="card">Loading live machine availability…</div>}
  {(page === 'overview' || page === 'session') && active && <section className="session-card"><div className="session-icon"><WashingMachine size={36}/></div><div className="session-text"><span className="eyebrow">YOUR {active.endsAt <= now ? 'FINISHED' : 'ACTIVE'} SESSION</span><h2>{state.machines.find(m => m.id === active.machineId)?.name || active.machineId} is {active.endsAt <= now ? 'ready to release' : 'doing its thing.'}</h2><p>Started {time(active.startedAt)} · Ends {time(active.endsAt)}</p><div className="progress"><div style={{width: `${Math.min(100, Math.max(0, (now - active.startedAt) / (active.endsAt - active.startedAt) * 100))}%`}}/></div></div><div className="session-timer"><strong>{remaining(active.endsAt, now)}</strong><small>remaining</small></div><div className="session-actions"><button className="secondary" disabled={busy || active.extensionMinutes >= 15 || active.endsAt <= now} onClick={() => act('extendSession', {sessionId:active.id,expectedVersion:active.version}, '15 minutes added to your session.')}>+ 15 minutes</button><button className="primary" disabled={busy} onClick={() => act('finishSession', {sessionId:active.id,expectedVersion:active.version}, 'Session finished. The machine is free.')}>Finish session<Check size={15}/></button></div></section>}
  {page === 'session' && !active && <section className="empty-state card"><CalendarClock size={42}/><h2>No laundry on the clock.</h2><p>Reserve a machine to start your next session.</p><button className="primary" onClick={() => setPage('overview')}>Find a machine<ArrowRight size={16}/></button></section>}
  {page === 'overview' && <><div className="stats"><div><span className="stat-icon green"><WashingMachine size={20}/></span><div><strong>{available.length}<small> / {state.machines.length}</small></strong><span>Machines available</span></div></div><div><span className="stat-icon cream"><Clock3 size={20}/></span><div><strong>{state.machines.filter(m => m.status === 'online' && m.activeEndsAt > now).length}</strong><span>Loads in progress</span></div></div><div><span className="stat-icon muted"><Wrench size={20}/></span><div><strong>{state.machines.filter(m => m.status === 'maintenance').length}</strong><span>Under maintenance</span></div></div></div>
  <div className="section-heading"><div><h2>Find your machine</h2><p>Availability updates as residents book and finish.</p></div><div className="filter" role="group" aria-label="Filter by floor">{['All floors',...new Set(state.machines.map(m => m.floor))].map(f => <button key={f} className={floor === f ? 'selected' : ''} onClick={() => setFloor(f)}>{f}</button>)}</div></div>
  <div className="machine-grid">{availableByFloor.map(machine => {const maintenance = machine.status === 'maintenance', occupied = !maintenance && machine.activeEndsAt > now; return <article className={`machine-card ${maintenance ? 'maintenance' : occupied ? 'occupied' : 'available'}`} key={machine.id}><div className="machine-top"><span className={`status-pill ${maintenance ? 'muted' : occupied ? 'amber' : 'green'}`}><i/>{maintenance ? 'Maintenance' : occupied ? 'In use' : 'Available'}</span><button className="icon-button" aria-label={`Report ${machine.name}`} onClick={() => {setDialog({kind:'reportMachine',machine});setDetail('');}}><Wrench size={15}/></button></div><div className="machine-visual"><WashingMachine size={85} strokeWidth={1.1}/>{!occupied && !maintenance && <span className="machine-sparkle">✦</span>}</div><h3>{machine.name}</h3><p>{machine.floor} · 7 kg capacity</p><div className="machine-divider"/><div className="machine-meta"><Clock3 size={14}/>{maintenance ? 'We’re getting it ready' : occupied ? `Available in ${remaining(machine.activeEndsAt, now)}` : '30, 45 or 60 min session'}</div><button className={maintenance || occupied ? 'reserve unavailable' : 'reserve'} disabled={busy || occupied || maintenance || (!!active && active.endsAt > now)} onClick={() => {setSelected(machine);setDuration(45);}}>{maintenance ? 'Temporarily unavailable' : occupied ? 'Currently washing' : 'Reserve machine'}{!maintenance && !occupied && <ArrowRight size={16}/>}</button>{state.user?.isAdmin && <div className="admin-actions"><button onClick={() => {setDialog({kind:occupied?'resolveMachine':'setMaintenance',machine});setDetail('');}}>{occupied ? 'Resolve session' : maintenance ? 'Return to service' : 'Set maintenance'}</button></div>}</article>;})}</div>
  {!state.loading && state.machines.length === 0 && <div className="card empty-state"><p>No machines have been configured. Ask an administrator to seed the laundry room.</p></div>}
  <div className="bottom-note"><ShieldCheck size={19}/><div><strong>A fairer laundry room.</strong><p>One active booking per resident. Please collect your clothes when your session ends.</p></div></div>
  {state.user.isAdmin && <section className="card reports"><h2>Machine reports</h2>{state.reports.filter(r => r.status === 'open').length === 0 ? <p>No open reports.</p> : state.reports.filter(r=>r.status==='open').map(report => <div className="report" key={report.id}><div><strong>{report.machineId}</strong><p>{report.reason}</p></div><button className="secondary" onClick={() => {setDialog({kind:'resolveReport',reportId:report.id});setDetail('');}}>Resolve report</button></div>)}</section>}</>}
  {page === 'history' && <section className="card history"><h2>Your past sessions</h2>{state.sessions.length === 0 ? <p>Your first laundry session will appear here.</p> : <div className="table-scroll"><table><thead><tr><th>Machine</th><th>Date</th><th>Duration</th><th>Status</th></tr></thead><tbody>{[...state.sessions].sort((a,b)=>b.startedAt-a.startedAt).map(session=><tr key={session.id}><td>{session.machineId.toUpperCase()}</td><td>{new Date(session.startedAt).toLocaleString()}</td><td>{session.durationMinutes + session.extensionMinutes} minutes</td><td><span className="status-pill green">{session.status}</span></td></tr>)}</tbody></table></div>}</section>}
  {page === 'guide' && <section className="guide-grid">{[{title:'Before you start',text:'Check pockets, separate colours, and keep the drum comfortably below its 7 kg capacity.',Icon:WashingMachine},{title:'Choose your time',text:'Pick a 30, 45, or 60 minute session. You can add one 15 minute extension while your session is active.',Icon:Clock3},{title:'When you finish',text:'Collect your clothes and finish your session. Leave the door open so the drum can dry.',Icon:CheckCircle2},{title:'Something feels wrong?',text:'Use the wrench on a machine card to report a problem. The hostel administrator can reconcile bookings and arrange maintenance.',Icon:Wrench}].map(({title,text,Icon})=><article className="card" key={title}><Icon size={27}/><h2>{title}</h2><p>{text}</p></article>)}</section>}
  <footer>Made for shared spaces. Built around your day.<span>WashBook</span></footer></main>
  {selected && <div className="modal-backdrop" onClick={()=>!busy&&setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="booking-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close booking" disabled={busy} onClick={()=>setSelected(null)}><X size={21}/></button><span className="modal-icon"><WashingMachine size={32}/></span><span className="eyebrow">LET’S GET THIS LOAD STARTED</span><h2 id="booking-title">Reserve {selected.name}</h2><p>{selected.floor} · Your session starts immediately.</p><label>How much time do you need?</label><div className="duration-options">{[30,45,60].map(m=><button key={m} className={duration === m ? 'selected' : ''} onClick={()=>setDuration(m)}><strong>{m}</strong><span>minutes</span>{duration===m&&<Check size={13}/>}</button>)}</div><div className="booking-summary"><span>Estimated finish</span><strong>{time(now+duration*60000)}</strong></div><p className="small">You can extend once by 15 minutes. Please collect your clothes on time.</p>{error && <p className="error-text" role="alert">{error}</p>}<button className="primary full" disabled={busy} onClick={()=>work(async()=>{await gateway!.act('bookMachine',{machineId:selected.id,durationMinutes:duration,expectedVersion:selected.version});setSelected(null);},'Your session has started.')}>{busy?'Reserving…':'Confirm reservation'}<ArrowRight size={16}/></button></section></div>}
  {dialog && <div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-labelledby="action-title" onSubmit={e=>{e.preventDefault();work(async()=>{await gateway!.act(dialog.kind,{...(dialog.machine?{machineId:dialog.machine.id,expectedVersion:dialog.machine.version,enabled:dialog.machine.status!=='maintenance'}:{}),...(dialog.reportId?{reportId:dialog.reportId}:{}),reason:detail});setDialog(null);},'The update was saved.');}}><button type="button" className="close" aria-label="Close action" disabled={busy} onClick={()=>setDialog(null)}><X size={21}/></button><Wrench size={32}/><h2 id="action-title">{dialog.kind==='reportMachine'?'Report a machine':dialog.kind==='setMaintenance'?'Update maintenance':dialog.kind==='resolveReport'?'Resolve report':'Resolve this session'}</h2><p>{dialog.kind==='resolveMachine'?'This releases the machine and closes its active session.':''}</p><label htmlFor="detail">{dialog.kind==='reportMachine'?'What happened?':'Resolution or reason'}</label><textarea id="detail" rows={4} minLength={3} maxLength={500} required value={detail} onChange={e=>setDetail(e.target.value)} placeholder="Add the details…"/>{error&&<p className="error-text" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy?'Saving…':'Save update'}<Check size={16}/></button></form></div>}
  </div>;
}
